### ISSUE TITLE
On Running client.js ERROR Occurs

### ISSUE THREAD

**Issue by kamidehlvi** [matteomattei/nodejs-ssl-mutual-authentication#1]
TLS Socket ERROR (Error: Client network socket disconnected before secure TLS connection was established)
Waiting for the debugger to disconnect...
Please help 
Socket.on method is not working  as per my understanding  we should use socket library instead please

**Comment by matteomattei** [comment]
The certificates stored in the repo were expired.
I just generated the new ones and updated. Anyway make sure to generate some new certificates and keys (as described in the original article) for your project.

Moreover, you would need to use one of the latest version of nodejs.
I just tested with node v16.x and it works fine.
